### ISSUE TITLE
Support for journeymaps, huskhomes

### ISSUE THREAD

**Issue by xhyrom** [sammyshear/Waypoints4Homes#1]
Hi, this plugin-mod is actually a brilliant idea. I'm thinking about what I can code for minecraft, but sometimes I don't have any idea.

Nevermind, I would like to see support for https://www.curseforge.com/minecraft/mc-mods/journeymap and https://modrinth.com/plugin/huskhomes

I think, I can create for this pull request. It's really good plugin-mod idea and I want to help If I can.

**Comment by sammyshear** [comment]
Hi! This sounds like a good addition. I think HuskHomes would be quite simple to add to the bukkit plugin as long as it lets you listen for some kind of custom event. Journeymap may require some more work due to the way I set it up in the fabric mod, but it shouldn't be a whole lot worse. If you think it's doable for you, I'd be happy to merge it. I can also take a look at Journeymap and HuskHomes to see what it would take to do.

**Comment by sammyshear** [comment]
I took a look at HuskHomes and it looks like it has basically the same [API](https://william278.net/docs/huskhomes/api-events) as EssentialsX as far as events go, so it would be pretty trivial to implement. Journeymap looks like it has a more robust [API](https://github.com/TeamJM/journeymap-api/blob/1.20.x_1.9-fabric/docs/howto.md) than Xaero's due to actually being designed as an API. So really as long as you can detect which mod is active on the client and which plugin is active on the server, it should be pretty easy to do both actual implementations. I don't think even think it should take too much refactoring to make it work though.

**Comment by sammyshear** [comment]
I went ahead and added support for these in commit [d3a8e4a](https://github.com/sammyshear/Waypoints4Homes/commit/d3a8e4a3f5fce0ca8d87cdea9b36f0b3f4def66d)

**Comment by xhyrom** [comment]
oh, cool, great job!
